/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as ApiMondayLogoutRouteImport } from './routes/api/monday/logout'
import { Route as ApiMondayLoginRouteImport } from './routes/api/monday/login'
import { Route as ApiMondayCallbackRouteImport } from './routes/api/monday/callback'
import { Route as ApiPublicMondayLogoutRouteImport } from './routes/api/public/monday/logout'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMondayLogoutRoute = ApiMondayLogoutRouteImport.update({
  id: '/api/monday/logout',
  path: '/api/monday/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMondayLoginRoute = ApiMondayLoginRouteImport.update({
  id: '/api/monday/login',
  path: '/api/monday/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMondayCallbackRoute = ApiMondayCallbackRouteImport.update({
  id: '/api/monday/callback',
  path: '/api/monday/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMondayLogoutRoute = ApiPublicMondayLogoutRouteImport.update({
  id: '/api/public/monday/logout',
  path: '/api/public/monday/logout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/monday/callback': typeof ApiMondayCallbackRoute
  '/api/monday/login': typeof ApiMondayLoginRoute
  '/api/monday/logout': typeof ApiMondayLogoutRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/monday/logout': typeof ApiPublicMondayLogoutRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/monday/callback': typeof ApiMondayCallbackRoute
  '/api/monday/login': typeof ApiMondayLoginRoute
  '/api/monday/logout': typeof ApiMondayLogoutRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/monday/logout': typeof ApiPublicMondayLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/monday/callback': typeof ApiMondayCallbackRoute
  '/api/monday/login': typeof ApiMondayLoginRoute
  '/api/monday/logout': typeof ApiMondayLogoutRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/monday/logout': typeof ApiPublicMondayLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/api/monday/callback'
    | '/api/monday/login'
    | '/api/monday/logout'
    | '/api/public/bootstrap-admin'
    | '/api/public/monday/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/'
    | '/api/monday/callback'
    | '/api/monday/login'
    | '/api/monday/logout'
    | '/api/public/bootstrap-admin'
    | '/api/public/monday/logout'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/'
    | '/api/monday/callback'
    | '/api/monday/login'
    | '/api/monday/logout'
    | '/api/public/bootstrap-admin'
    | '/api/public/monday/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiMondayCallbackRoute: typeof ApiMondayCallbackRoute
  ApiMondayLoginRoute: typeof ApiMondayLoginRoute
  ApiMondayLogoutRoute: typeof ApiMondayLogoutRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  ApiPublicMondayLogoutRoute: typeof ApiPublicMondayLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monday/logout': {
      id: '/api/monday/logout'
      path: '/api/monday/logout'
      fullPath: '/api/monday/logout'
      preLoaderRoute: typeof ApiMondayLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monday/login': {
      id: '/api/monday/login'
      path: '/api/monday/login'
      fullPath: '/api/monday/login'
      preLoaderRoute: typeof ApiMondayLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monday/callback': {
      id: '/api/monday/callback'
      path: '/api/monday/callback'
      fullPath: '/api/monday/callback'
      preLoaderRoute: typeof ApiMondayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/monday/logout': {
      id: '/api/public/monday/logout'
      path: '/api/public/monday/logout'
      fullPath: '/api/public/monday/logout'
      preLoaderRoute: typeof ApiPublicMondayLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiMondayCallbackRoute: ApiMondayCallbackRoute,
  ApiMondayLoginRoute: ApiMondayLoginRoute,
  ApiMondayLogoutRoute: ApiMondayLogoutRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  ApiPublicMondayLogoutRoute: ApiPublicMondayLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
